export const BLOG_TYPE_LOAD_REQUEST = "BLOG_TYPE_LOAD_REQUEST";
export const BLOG_TYPE_LOAD_SUCCESS = "BLOG_TYPE_LOAD_SUCCESS";
export const BLOG_TYPE_LOAD_FAIL = "BLOG_TYPE_LOAD_FAIL";
export const BLOG_TYPE_LOAD_RESET = "BLOG_TYPE_LOAD_RESET";

export const CREATE_BLOG_TYPE_REQUEST = "CREATE_JOB_TYPE_REQUEST";
export const CREATE_BLOG_TYPE_SUCCESS = "CREATE_JOB_TYPE_SUCCESS";
export const CREATE_BLOG_TYPE_FAIL = "CREATE_JOB_TYPE_FAIL";
export const CREATE_BLOG_TYPE_RESET = "CREATE_JOB_TYPE_RESET";

export const DELETE_BLOG_TYPE_REQUEST = "DELETE_BLOG_TYPE_REQUEST";
export const DELETE_BLOG_TYPE_SUCCESS = "DELETE_BLOG_TYPE_SUCCESS";
export const DELETE_BLOG_TYPE_FAIL = "DELETE_BLOG_TYPE_FAIL";
export const DELETE_BLOG_TYPE_RESET = "DELETE_BLOG_TYPE_RESET";

export const EDIT_BLOG_TYPE_REQUEST = "EDIT_BLOG_TYPE_REQUEST";
export const EDIT_BLOG_TYPE_SUCCESS = "EDIT_BLOG_TYPE_SUCCESS";
export const EDIT_BLOG_TYPE_FAIL = "EDIT_BLOG_TYPE_FAIL";
export const EDIT_BLOG_TYPE_RESET = "EDIT_BLOG_TYPE_RESET";