export const BLOG_LOAD_REQUEST = "BLOG_LOAD_REQUEST";
export const BLOG_LOAD_SUCCESS = "BLOG_LOAD_SUCCESS";
export const BLOG_LOAD_FAIL = "BLOG_LOAD_FAIL";
export const BLOG_LOAD_RESET = "BLOG_LOAD_RESET";

export const ADMIN_BLOG_LOAD_REQUEST = "ADMIN_BLOG_LOAD_REQUEST";
export const ADMIN_BLOG_LOAD_SUCCESS = "ADMIN_BLOG_LOAD_SUCCESS";
export const ADMIN_BLOG_LOAD_FAIL = "ADMIN_BLOG_LOAD_FAIL";
export const ADMIN_BLOG_LOAD_RESET = "ADMIN_BLOG_LOAD_RESET";

export const BLOG_LOAD_SINGLE_REQUEST = "BLOG_LOAD_SINGLE_REQUEST";
export const BLOG_LOAD_SINGLE_SUCCESS = "BLOG_LOAD_SINGLE_SUCCESS";
export const BLOG_LOAD_SINGLE_FAIL = "BLOG_LOAD_SINGLE_FAIL";
export const BLOG_LOAD_SINGLE_RESET = "BLOG_LOAD_SINGLE_RESET";

export const ALL_USER_LOAD_REQUEST = "ALL_USER_LOAD_REQUEST";
export const ALL_USER_LOAD_SUCCESS = "ALL_USER_LOAD_SUCCESS";
export const ALL_USER_LOAD_FAIL = "ALL_USER_LOAD_FAIL";
export const ALL_USER_LOAD_RESET = "ALL_USER_LOAD_RESET";

export const REGISTER_BLOG_REQUEST = "REGISTER_BLOG_REQUEST";
export const REGISTER_BLOG_SUCCESS = "REGISTER_BLOG_SUCCESS";
export const REGISTER_BLOG_FAIL = "REGISTER_BLOG_FAIL";
export const REGISTER_BLOG_RESET = "REGISTER_BLOG_RESET";

export const DELETE_BLOG_REQUEST = "DELETE_BLOG_REQUEST";
export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";
export const DELETE_BLOG_FAIL = "DELETEOG_FAIL";
export const DELETE_BLOG_RESET = "DELETE_BLOG_RESET";
// export const CREATOR_BLOG_LOAD_REQUEST = "CREATOR_BLOG_LOAD_REQUEST";
// export const CREATOR_BLOG_LOAD_SUCCESS = "CREATOR_BLOG_LOAD_SUCCESS";
// export const CREATOR_BLOG_LOAD_FAIL = "CREATOR_BLOG_LOAD_FAIL";
// export const CREATOR_BLOG_LOAD_RESET = "CREATOR_BLOG_LOAD_RESET";
