
export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_SIGNIN_RESET = "USER_SIGNIN_RESET";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS"; 
export const USER_LOGOUT_FAIL =  "USER_LOGOUT_FAIL";
export const USER_LOGOUT_RESET = "USER_LOGOUT_RESET";

export const USER_LOAD_REQUEST = "USER_LOAD_REQUEST";
export const USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS";
export const USER_LOAD_FAIL = "USER_LOAD_FAIL";
export const USER_LOAD_RESET = "USER_LOAD_RESET";

export const USER_APPLY_BLOG_REQUEST = "USER_APPLY_BLOG_REQUEST";
export const USER_APPLY_BLOG_SUCCESS = "USER_APPLY_BLOG_SUCCESS";
export const USER_APPLY_BLOG_FAIL = "USER_APPLY_BLOG_FAIL";
export const USER_APPLY_BLOG_RESET = "USER_APPLY_BLOG_RESET";

export const CREATOR_BLOG_REQUEST = "CREATOR_BLOG_REQUEST";
export const CREATOR_BLOG_SUCCESS = "CREATOR_BLOG_SUCCESS";
export const CREATOR_BLOG_FAIL = "CREATOR_BLOG_FAIL";
export const CREATOR_BLOG_RESET = "CREATOR_BLOG_RESET";

export const ALL_USER_LOAD_REQUEST = "ALL_USER_LOAD_REQUEST";
export const ALL_USER_LOAD_SUCCESS = "ALL_USER_LOAD_SUCCESS";
export const ALL_USER_LOAD_FAIL = "ALL_USER_LOAD_FAIL";
export const ALL_USER_LOAD_RESET = "ALL_USER_LOAD_RESET";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";
export const USER_SIGNUP_RESET = "USER_SIGNUP_RESET";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";
export const USER_DELETE_RESET = "USER_DELETE_RESET";

export const GET_APPLICANT_REQUEST = "GET_APPLICANT_REQUEST";
export const GET_APPLICANT_SUCCESS = "GET_APPLICANT_SUCCESS";
export const GET_APPLICANT_FAIL = "GET_APPLICANT_FAIL";
export const GET_APPLICANT_RESET = "GET_APPLICANT_RESET";

export const UPDATE_VIDEO_PROGRESS_REQUEST = 'UPDATE_VIDEO_PROGRESS_REQUEST';
export const UPDATE_VIDEO_PROGRESS_SUCCESS = 'UPDATE_VIDEO_PROGRESS_SUCCESS';
export const UPDATE_VIDEO_PROGRESS_FAIL = 'UPDATE_VIDEO_PROGRESS_FAIL';
export const UPDATE_VIDEO_PROGRESS_RESET = 'UPDATE_VIDEO_PROGRESS_RESET';